name: Publish Docker Image
permissions:
  contents: read
on:
    release:
        types: [published]
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Log in to Quay.io
          uses: docker/login-action@v1
          with:
            registry: quay.io
            username: ${{ secrets.QUAY_USERNAME }}
            password: ${{ secrets.QUAY_PASSWORD }}
        - name: Build and push Docker image to Docker Hub
          uses: docker/build-push-action@v2
          with:
            push: true
            platforms: linux/amd64,linux/arm64
            file: docker/images/services.Dockerfile
            context: .
            tags: ${{ vars.DOCKER_REPOSITORY }}/xformer:${{ github.ref_name }}, ${{ vars.DOCKER_REPOSITORY }}/xformer:latest
        - name: Build and push Docker image to Quay.io
          uses: docker/build-push-action@v2
          with:
            push: true
            platforms: linux/amd64,linux/arm64
            file: docker/images/services.Dockerfile
            context: .
            tags: quay.io/${{ vars.QUAY_REPOSITORY }}/xformer:${{ github.ref_name }}, ${{ vars.DOCKER_REPOSITORY }}/xformer:latest
